//! SeaORM Entity Types
//!
//! These are database entities generated by sea-orm-codegen.
//! They belong in the infrastructure layer as they are persistence concerns.

pub mod prelude;
pub mod roles;
pub mod user_roles;
pub mod users;

pub use prelude::*;
